CREATE TABLE preference (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    label VARCHAR(50) NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    INDEX IDX_PREFERENCE_USER (user_id)
);