ALTER TABLE car
ADD CONSTRAINT FK_CAR_USER FOREIGN KEY (user_id) REFERENCES user (id),
ADD CONSTRAINT FK_CAR_BRAND FOREIGN KEY (brand_id) REFERENCES brand (id),
ADD CONSTRAINT FK_CAR_ENGINE_TYPE FOREIGN KEY (engine_type_id) REFERENCES engine_type (id),
ADD CONSTRAINT FK_CAR_COLOR FOREIGN KEY (color_id) REFERENCES color (id);