CREATE TABLE user (
    id INT AUTO_INCREMENT NOT NULL,
    pseudo VARCHAR(30) NOT NULL,
    email VARCHAR(180) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME DEFAULT NULL,
    active TINYINT(1) NOT NULL,
    first_name VARCHAR(50) DEFAULT NULL,
    last_name VARCHAR(50) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    phone_number VARCHAR(17) DEFAULT NULL,
    photo_name VARCHAR(255) DEFAULT NULL,
    date_of_birth DATE DEFAULT NULL,
    pets_allowed TINYINT(1) DEFAULT NULL,
    smokers_allowed TINYINT(1) DEFAULT NULL,
    sum_of_ratings INT DEFAULT NULL,
    number_of_ratings INT DEFAULT NULL,
    credits INT NOT NULL,
    PRIMARY KEY(id),
    UNIQUE INDEX UNIQ_USER_PSEUDO (email),
    UNIQUE INDEX UNIQ_USER_PHONE_NUMBER (phone_number),
    UNIQUE INDEX UNIQ_USER_PHOTO_NAME (photo_name)
);